### PR TITLE
bitrig support

### PR DESCRIPTION
**Pull request by dhuseby**
This adds Bitrig support to the version of jemalloc (b001609) currently used by Rust.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Have you tried sending this upstream to jemalloc as well? In general we try to be sure to land all patches there first before our own repos, and it looks like they'd be quite welcoming of this!

**Comment by dhuseby** [comment]
@alexcrichton I am upstreaming this patch [here](https://github.com/jemalloc/jemalloc/pull/194).

**Comment by dhuseby** [comment]
@alexcrichton this change was just upstreamed to jemalloc: https://github.com/jemalloc/jemalloc/commit/970fcfbca5dffda921394172c7298d274eebfd0e

**Comment by alexcrichton** [comment]
Yay! Can you make a new PR with the included changes?

**Pull request closed without merging**
