### PR TITLE
adding support for bitrig

### PR DESCRIPTION
**Pull request by dhuseby**
(cherry picked from commit 970fcfbca5dffda921394172c7298d274eebfd0e)

Conflicts:
    configure.ac

### CODE REVIEW

**Comment by dhuseby** [comment]
oops, nvrmnd, already landed I guess.

**Comment by dhuseby** [comment]
@alexcrichton Wait, the change landed in dev/master.  Yes, I do want to cherry pick this.

**Comment by dhuseby** [comment]
@alexcrichton I'm trying to get my jemalloc bitrig changes into the current rust build.  Even though we've already merged in my changes in the dev branch, this change needs to land here also.

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
